<?php
session_start();
require_once '../config/database.php';

// Check if user is logged in and is admin
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header('Location: ../login.php');
    exit();
}

// Get report parameters
$report_type = $_GET['report_type'] ?? 'orders_summary';
$date_from = $_GET['date_from'] ?? date('Y-m-01');
$date_to = $_GET['date_to'] ?? date('Y-m-d');

// Create CSV content
$filename = "TailorTrack_Report_" . $report_type . "_" . date('Y-m-d_His') . ".csv";
$output = fopen('php://output', 'w');

// Set headers for CSV download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Pragma: no-cache');
header('Expires: 0');

// Add UTF-8 BOM for Excel to recognize encoding
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

try {
    if ($report_type === 'orders_summary') {
        // Header
        fputcsv($output, ['TAILORTRACK - ORDERS SUMMARY REPORT']);
        fputcsv($output, ['Period: ' . date('d M Y', strtotime($date_from)) . ' to ' . date('d M Y', strtotime($date_to))]);
        fputcsv($output, ['Generated: ' . date('d M Y, g:i A')]);
        fputcsv($output, ['Generated By: ' . $_SESSION['full_name']]);
        fputcsv($output, []);

        // Summary Statistics
        $stmt = $pdo->prepare("
            SELECT
                COUNT(*) as total_orders,
                SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as completed_orders,
                SUM(CASE WHEN status = 'paid' THEN 1 ELSE 0 END) as paid_orders,
                SUM(CASE WHEN status = 'cancel' THEN 1 ELSE 0 END) as cancelled_orders,
                SUM(total_amount) as total_revenue,
                AVG(total_amount) as avg_order_value
            FROM orders
            WHERE DATE(created_at) BETWEEN ? AND ?
        ");
        $stmt->execute([$date_from, $date_to]);
        $summary = $stmt->fetch();

        fputcsv($output, ['SUMMARY STATISTICS']);
        fputcsv($output, ['Total Orders', $summary['total_orders']]);
        fputcsv($output, ['Total Revenue', 'RM ' . number_format($summary['total_revenue'], 2)]);
        fputcsv($output, ['Average Order Value', 'RM ' . number_format($summary['avg_order_value'], 2)]);
        fputcsv($output, ['Completed Orders', $summary['completed_orders']]);
        fputcsv($output, ['Paid Orders', $summary['paid_orders']]);
        fputcsv($output, ['Cancelled Orders', $summary['cancelled_orders']]);
        fputcsv($output, []);

        // Orders by Type
        $stmt = $pdo->prepare("
            SELECT order_type, COUNT(*) as count, SUM(total_amount) as revenue
            FROM orders
            WHERE DATE(created_at) BETWEEN ? AND ?
            GROUP BY order_type
            ORDER BY count DESC
        ");
        $stmt->execute([$date_from, $date_to]);
        $orders_by_type = $stmt->fetchAll();

        fputcsv($output, ['ORDERS BY TYPE']);
        fputcsv($output, ['Order Type', 'Count', 'Revenue']);
        $total_count = 0;
        $total_revenue = 0;
        foreach ($orders_by_type as $type) {
            fputcsv($output, [
                ucwords(str_replace('_', ' ', $type['order_type'])),
                $type['count'],
                'RM ' . number_format($type['revenue'], 2)
            ]);
            $total_count += $type['count'];
            $total_revenue += $type['revenue'];
        }
        fputcsv($output, ['TOTAL', $total_count, 'RM ' . number_format($total_revenue, 2)]);
        fputcsv($output, []);

        // Orders by Status
        $stmt = $pdo->prepare("
            SELECT status, COUNT(*) as count
            FROM orders
            WHERE DATE(created_at) BETWEEN ? AND ?
            GROUP BY status
            ORDER BY count DESC
        ");
        $stmt->execute([$date_from, $date_to]);
        $orders_by_status = $stmt->fetchAll();

        fputcsv($output, ['ORDERS BY STATUS']);
        fputcsv($output, ['Status', 'Count', 'Percentage']);
        $total_status_count = array_sum(array_column($orders_by_status, 'count'));
        foreach ($orders_by_status as $status) {
            $percentage = ($status['count'] / $total_status_count) * 100;
            fputcsv($output, [
                ucfirst(str_replace('_', ' ', $status['status'])),
                $status['count'],
                number_format($percentage, 1) . '%'
            ]);
        }
        fputcsv($output, ['TOTAL', $total_status_count, '100.0%']);

    } elseif ($report_type === 'staff_performance') {
        // Header
        fputcsv($output, ['TAILORTRACK - STAFF PERFORMANCE REPORT']);
        fputcsv($output, ['Period: ' . date('d M Y', strtotime($date_from)) . ' to ' . date('d M Y', strtotime($date_to))]);
        fputcsv($output, ['Generated: ' . date('d M Y, g:i A')]);
        fputcsv($output, ['Generated By: ' . $_SESSION['full_name']]);
        fputcsv($output, []);

        // Get Staff Performance Data
        $stmt = $pdo->prepare("
            SELECT
                u.user_id,
                u.full_name,
                u.role,
                COUNT(CASE WHEN u.role = 'cashier' THEN o.order_id END) as orders_created,
                COUNT(CASE WHEN u.role = 'tailor' AND o.assigned_tailor = u.user_id THEN o.order_id END) as orders_assigned,
                COUNT(CASE WHEN u.role = 'tailor' AND o.assigned_tailor = u.user_id AND o.status = 'completed' THEN 1 END) as orders_completed,
                SUM(CASE WHEN u.role = 'cashier' THEN o.total_amount ELSE 0 END) as revenue_generated
            FROM users u
            LEFT JOIN orders o ON (
                (u.role = 'cashier' AND o.created_by = u.user_id) OR
                (u.role = 'tailor' AND o.assigned_tailor = u.user_id)
            ) AND DATE(o.created_at) BETWEEN ? AND ?
            WHERE u.role IN ('cashier', 'tailor')
            GROUP BY u.user_id, u.full_name, u.role
            ORDER BY u.role, u.full_name
        ");
        $stmt->execute([$date_from, $date_to]);
        $staff_data = $stmt->fetchAll();

        fputcsv($output, ['STAFF PERFORMANCE OVERVIEW']);
        fputcsv($output, ['Staff Name', 'Role', 'Orders Created', 'Orders Assigned', 'Orders Completed', 'Revenue Generated', 'Performance %']);

        foreach ($staff_data as $staff) {
            $completion_rate = 0;
            if ($staff['role'] === 'tailor' && $staff['orders_assigned'] > 0) {
                $completion_rate = ($staff['orders_completed'] / $staff['orders_assigned']) * 100;
            } elseif ($staff['role'] === 'cashier' && $staff['orders_created'] > 0) {
                $completion_rate = 100;
            }

            fputcsv($output, [
                $staff['full_name'],
                ucfirst($staff['role']),
                $staff['orders_created'] > 0 ? $staff['orders_created'] : '-',
                $staff['orders_assigned'] > 0 ? $staff['orders_assigned'] : '-',
                $staff['orders_completed'] > 0 ? $staff['orders_completed'] : '-',
                'RM ' . number_format($staff['revenue_generated'], 2),
                number_format($completion_rate, 1) . '%'
            ]);
        }

    } elseif ($report_type === 'financial') {
        // Header
        fputcsv($output, ['TAILORTRACK - FINANCIAL REPORT']);
        fputcsv($output, ['Period: ' . date('d M Y', strtotime($date_from)) . ' to ' . date('d M Y', strtotime($date_to))]);
        fputcsv($output, ['Generated: ' . date('d M Y, g:i A')]);
        fputcsv($output, ['Generated By: ' . $_SESSION['full_name']]);
        fputcsv($output, []);

        // Get Financial Data
        $stmt = $pdo->prepare("
            SELECT
                DATE(created_at) as order_date,
                COUNT(*) as order_count,
                SUM(total_amount) as daily_revenue,
                SUM(CASE WHEN status = 'paid' THEN total_amount ELSE 0 END) as paid_amount,
                SUM(CASE WHEN status != 'paid' AND status != 'cancel' THEN total_amount ELSE 0 END) as pending_amount
            FROM orders
            WHERE DATE(created_at) BETWEEN ? AND ?
            GROUP BY DATE(created_at)
            ORDER BY order_date
        ");
        $stmt->execute([$date_from, $date_to]);
        $financial_data = $stmt->fetchAll();

        // Summary
        $total_revenue = 0;
        $total_paid = 0;
        $total_pending = 0;
        $total_orders = 0;

        foreach ($financial_data as $day) {
            $total_revenue += $day['daily_revenue'];
            $total_paid += $day['paid_amount'];
            $total_pending += $day['pending_amount'];
            $total_orders += $day['order_count'];
        }

        fputcsv($output, ['FINANCIAL SUMMARY']);
        fputcsv($output, ['Total Revenue', 'RM ' . number_format($total_revenue, 2)]);
        fputcsv($output, ['Paid Amount', 'RM ' . number_format($total_paid, 2)]);
        fputcsv($output, ['Pending Amount', 'RM ' . number_format($total_pending, 2)]);
        fputcsv($output, ['Total Orders', $total_orders]);
        fputcsv($output, []);

        // Daily breakdown
        fputcsv($output, ['DAILY FINANCIAL DETAILS']);
        fputcsv($output, ['Date', 'Orders', 'Daily Revenue', 'Paid Amount', 'Pending Amount']);

        foreach ($financial_data as $day) {
            fputcsv($output, [
                date('d M Y', strtotime($day['order_date'])),
                $day['order_count'],
                'RM ' . number_format($day['daily_revenue'], 2),
                'RM ' . number_format($day['paid_amount'], 2),
                'RM ' . number_format($day['pending_amount'], 2)
            ]);
        }

        fputcsv($output, [
            'TOTAL',
            $total_orders,
            'RM ' . number_format($total_revenue, 2),
            'RM ' . number_format($total_paid, 2),
            'RM ' . number_format($total_pending, 2)
        ]);
    }

} catch (PDOException $e) {
    error_log("Excel export error: " . $e->getMessage());
    fputcsv($output, ['Error generating report. Please try again.']);
}

fclose($output);
exit();
?>
